function [outFreq, gof] = createFitSin(x, y)
%CREATEFIT(X,YPOOR4)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: yPoor4
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 21-Sep-2018 17:16:03



%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.

persistent fit_sin
persistent opts

if isempty(fit_sin)

    fit_sin = fittype( 'sin1' );
%    set(fit_sin, 'PersistentMemory', true)

end

if isempty(opts)
    
    opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
    opts.Display = 'Off';
    opts.Lower = [-Inf 2 -Inf]*2*pi;
    opts.Upper = [Inf 10 Inf]*2*pi;
%    set(opts, 'PersistentMemory', true)

end
% Fit model to data.
[fitresult, gof] = fit( xData, yData, fit_sin, opts );
gof = gof.adjrsquare;
C = coeffvalues(fitresult);
outFreq = C(2)/(2*pi);


end

